version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/key-logger"
      - "/packages/level-logger"
      - "/packages/logger-type"
      - "/packages/loglevel-type"
      - "/packages/prefix-logger"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]