name: Key Logger CI/CD
on:
  push:
    branches: [main]
    paths:
      - "packages/key-logger/**"
      - ".github/workflows/key-logger.yml"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/module.yml"
  pull_request:
    branches: [main]
    paths:
      - "packages/key-logger/**"
      - ".github/workflows/key-logger.yml"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/module.yml"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  module-flow:
    uses: ./.github/workflows/module.yml
    secrets: inherit
    with:
      package-path: packages/key-logger
